name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        Thank you for taking the time to report a bug. Please provide as much detail as possible to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: The server crashes when executing a query with...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the bug
      placeholder: |
        1. Configure the server with...
        2. Execute query...
        3. Observe error...
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The query should return...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, the server threw an error...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      value: |
        - Neo4j YASS MCP Version:
        - Neo4j Version:
        - Python Version:
        - OS:
        - Transport Mode (stdio/http/sse):
        - LLM Provider:
        - Installation Method (pip/uv/docker):
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please include any relevant log output
      placeholder: |
        ```
        Paste logs here
        ```
      render: shell

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Please share relevant configuration (remove any sensitive data)
      placeholder: |
        ```env
        MCP_TRANSPORT=stdio
        NEO4J_URI=bolt://localhost:7687
        # ... other settings
        ```
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: This issue started occurring after upgrading to...
