name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Thank you for suggesting a new feature! Please check the [Future Features Roadmap](https://github.com/hdjebar/neo4j-yass-mcp/tree/main/docs/FutureFeatures) to see if your feature is already planned.

  - type: dropdown
    id: feature_category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - Security Enhancement
        - Performance Optimization
        - Query Capabilities
        - LLM Integration
        - Monitoring & Observability
        - Developer Experience
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: As a user, I find it difficult to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
      placeholder: I would like to see a feature that...
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Provide specific use cases or scenarios where this feature would be valuable
      placeholder: |
        1. When working with large graphs, I need to...
        2. For compliance reporting, it would be helpful to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried using... but it doesn't work because...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my use case)
        - High (would significantly improve my workflow)
        - Medium (would be nice to have)
        - Low (minor improvement)

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to write documentation for this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: |
        Here's how a similar feature works in another project...
