name: Security Vulnerability Report
description: Report a security vulnerability or security-related issue
title: "[SECURITY] "
labels: ["security", "needs-triage"]
assignees:
  - hdjebar

body:
  - type: markdown
    attributes:
      value: |
        ## Security Vulnerability Report

        Thank you for helping to keep Neo4j YASS MCP secure. Please provide as much detail as possible.

        **⚠️ IMPORTANT**: If this is a critical vulnerability that could be exploited, please report it privately via email to hdjebar@gmail.com instead of creating a public issue.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Critical (Remote Code Execution, Data Breach)
        - High (Authentication Bypass, Privilege Escalation)
        - Medium (Information Disclosure, DoS)
        - Low (Minor Information Leak, Configuration Issue)
    validations:
      required: true

  - type: dropdown
    id: vulnerability_type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      multiple: true
      options:
        - Cypher Injection
        - Authentication/Authorization
        - Cross-Site Scripting (XSS)
        - SQL/NoSQL Injection
        - Path Traversal
        - Information Disclosure
        - Denial of Service (DoS)
        - Insecure Configuration
        - Dependency Vulnerability
        - UTF-8/Unicode Attack
        - Other (please describe)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Provide a clear and detailed description of the security vulnerability
      placeholder: |
        Example: The query sanitizer fails to properly escape certain UTF-8 characters, allowing an attacker to bypass Cypher injection protection...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the vulnerability
      placeholder: |
        1. Configure the server with...
        2. Send a request with payload...
        3. Observe the unexpected behavior...
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Security Impact
      description: What is the potential impact of this vulnerability?
      placeholder: |
        - Data that could be exposed or compromised
        - Systems that could be affected
        - Potential for exploitation
        - Scope of affected users/deployments
    validations:
      required: true

  - type: textarea
    id: affected_versions
    attributes:
      label: Affected Versions
      description: Which versions are affected by this vulnerability?
      placeholder: |
        - v1.0.0
        - main branch (commit SHA: abc123...)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Provide details about the environment where the vulnerability was discovered
      value: |
        - Neo4j YASS MCP Version:
        - Neo4j Version:
        - Python Version:
        - OS:
        - Transport Mode (stdio/http/sse):
        - LLM Provider:
    validations:
      required: true

  - type: textarea
    id: proof_of_concept
    attributes:
      label: Proof of Concept (PoC)
      description: If applicable, provide a proof of concept or example exploit
      placeholder: |
        ```python
        # Example exploit code or malicious input
        payload = "MATCH (n) WHERE n.name = '" + malicious_input + "' RETURN n"
        ```
      render: python

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for fixing this vulnerability, please share them
      placeholder: |
        - Update the sanitizer to properly escape...
        - Add validation for...
        - Implement rate limiting on...

  - type: textarea
    id: references
    attributes:
      label: References
      description: Provide any relevant references (CVEs, articles, similar vulnerabilities, etc.)
      placeholder: |
        - CVE-2024-XXXXX
        - https://owasp.org/...
        - Similar vulnerability in project X: https://...

  - type: checkboxes
    id: responsible_disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm you understand our responsible disclosure policy
      options:
        - label: I have not publicly disclosed this vulnerability
          required: true
        - label: I will allow reasonable time for a fix before public disclosure
          required: true
        - label: For critical vulnerabilities, I have contacted the maintainer privately at hdjebar@gmail.com
          required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, logs, or information about the vulnerability
      placeholder: |
        Any additional information that might help in understanding or reproducing the issue.
